# Generated by config_brpc.sh, don't modify manually
SYSTEM=Linux
HDRS=/usr/include/ /usr/local/include/ /search/odin/zhangjun/tools/protobuf-3.7.1/include/
LIBS=/usr/lib64 /usr/local/lib64 /search/odin/zhangjun/tools/protobuf-3.7.1/lib
PROTOC=/search/odin/zhangjun/tools/protobuf-3.7.1/bin/protoc
PROTOBUF_HDR=/search/odin/zhangjun/tools/protobuf-3.7.1/include/
CC=gcc -std=gnu99
CXX=g++ -std=gnu++0x
GCC_VERSION=40805
STATIC_LINKINGS=
DYNAMIC_LINKINGS=-lpthread -lssl -lcrypto -ldl -lz -lrt -lgflags -lleveldb -lprotobuf
CPPFLAGS=-DBRPC_WITH_GLOG=0 -DGFLAGS_NS=gflags -g
ifeq ($(NEED_LIBPROTOC), 1)
   $(error "Fail to find libprotoc")
endif
ifeq ($(NEED_GPERFTOOLS), 1)
    DYNAMIC_LINKINGS+=-ltcmalloc_and_profiler
endif
ifeq ($(NEED_GTEST), 1)
    DYNAMIC_LINKINGS+=-lgtest
    DYNAMIC_LINKINGS+=-lgtest_main
endif
